image:
  file: .gitpod.Dockerfile
tasks:
  - name: Run project
    init: |
      ### Setup flutter packages
      dart --disable-analytics
      flutter pub get
      flutter create --platforms linux .

      ### Build for common targets
      # flutter build -v linux
      # flutter build -v web

      ### If you want to build for android, consider uncommenting the below lines
      # flutter build -v bundle
      # flutter build -v appbundle
      # flutter build -v apk
    
    command: |
      ### Tries build
      flutter build -v linux || (

        ### Retries install on error
        dart --disable-analytics
        flutter pub get
        flutter create --platforms linux .
        flutter build -v linux
      )

      ### Starts application
      flutter run -d linux

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter
